In [1]:
import pandas as pd 
import numpy as np

In [7]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2026-06-01', periods=8)
}
df=pd.DataFrame(data)

In [8]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2026-06-01
1        B    S1    200        15 2026-06-02
2        A    S2    150        12 2026-06-03
3        B    S2    250        18 2026-06-04
4        A    S1    120         8 2026-06-05
5        B    S2    180        20 2026-06-06
6        A    S2    200        15 2026-06-07
7        B    S1    300        25 2026-06-08

In [16]:
print(df.groupby('Store')['Sales'].sum())

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [24]:
# Group by Category and Store
df.groupby('Store')['Sales'].agg([
    'sum',
    'mean',
    'count',
    'median',
    'max',
])

       sum   mean  count  median  max
Store
S1     720  180.0      4   160.0  300
S2     780  195.0      4   190.0  250